name: CI

on:
  push:
  pull_request:
    branches: [dependabot/**]

jobs:
  nodejs:
    name: Node.js
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Packages
        run: npm ci

      - name: Build
        run: npm run build:git

      - name: Lint (TS)
        run: npm run ci:lint:ts
